name: currency_report
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  characters: ^1.2.0
  currency_text_input_formatter: ^2.1.0
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_bloc: ^0.30.1
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl: ^0.17.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
